FROM python:3.11
EXPOSE 8051
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt 
COPY . ./
ENTRYPOINT [ "streamlit","run","user.py","--server.port=8051","--server.address=0.0.0.0" ]